// This is an Allure 3 config file, not a nukadoko one. Allure 3's own
// generate/report tooling auto-detects allurerc.{js,mjs,cjs,json,yaml,yml}
// from the current working directory (no --config flag needed), and reads
// its own categories field from there, never from a results directory's
// categories.json (that format is Allure 2's).
//
// What this does: maps each nukadoko.failure=<kind> result label to an
// Allure category name, one rule per ErrorKind. Generated by `nuka init`
// from src/report/allure/categories.ts's own NAME_BY_KIND, the source of
// truth for these names.
//
// historyPath points Allure's own generate/watch/report at a file (not a
// directory) where each run's own history point is appended, kept beside
// the disposable allure-results/ directory rather than inside it so
// clearing results between runs (a fresh CI checkout, a local rerun)
// never discards it. Without this, Allure never builds history, trend, or
// flaky-across-runs detection, no matter how stable a scenario's own
// identity is.
//
// Already have your own allurerc? Merge this categories array (and
// historyPath, if you don't already set one) into it instead of
// replacing the whole file.
//
// Using Allure 2 instead? This file is not needed: nukadoko's own emitter
// already writes a matching categories.json into export/allure-results/ every run.
export default {
  historyPath: ".nukadoko/export/allure-history.jsonl",
  categories: [
    {
      name: "Contract: args failed the step's schema",
      matchers: [{ labels: { "nukadoko.failure": "args_invalid" } }],
    },
    {
      name: "Contract: result failed the step's schema",
      matchers: [{ labels: { "nukadoko.failure": "result_invalid" } }],
    },
    {
      name: "Contract: the step's text couldn't bind",
      matchers: [{ labels: { "nukadoko.failure": "binding_invalid" } }],
    },
    {
      name: "Contract: a World key's write failed its schema",
      matchers: [{ labels: { "nukadoko.failure": "world_invalid" } }],
    },
    {
      name: "Timeout",
      matchers: [{ labels: { "nukadoko.failure": "timeout" } }],
    },
    {
      name: "Compat: unsupported step shape",
      matchers: [{ labels: { "nukadoko.failure": "unsupported" } }],
    },
    {
      name: "Step error",
      matchers: [{ labels: { "nukadoko.failure": "step_error" } }],
    },
  ],
};
